'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import React from "react";
import "./globals.css";
import { GoArrowRight, GoArrowLeft } from "react-icons/go";
import Footer from "./ui/components/footer/page";
import Header from "./ui/components/header/page";
const geistSans = localFont({
   src: "./fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
});
const geistMono = localFont({
   src: "./fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
});

// export const metadata: Metadata = {
//    title: "Create Next App",
//    description: "Generated by create next app",
// };

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="ru">
         <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
               <div className={`root-layout`}>
                  <div className="header">
                     <Header />
                  </div>
                  <main className="content">{children}</main>
                  <footer className={"footer"}>
                     <Footer />
                  </footer>
               </div>
            </body >
         </body >
      </html >
   );
}
